// The three reels. Each is a flat list of strings; order does not matter, the
// slot machine shuffles at spin time. Keep entries short enough to fit a reel
// window on a phone (two lines at most).

// Familiar genres and sub-genres a viewer already has a feel for.
export const GENRES = [
  'Buddy comedy', 'Romantic comedy', 'Screwball comedy', 'Slapstick comedy', 'Dark comedy',
  'Workplace comedy', 'Fish-out-of-water comedy', 'Stoner comedy', 'Teen comedy', 'Wedding comedy',
  'Satire', 'Parody', 'Odd couple', 'Bromance', 'Enemies-to-lovers',
  'Second-chance romance', 'Forbidden love', 'Long-distance romance', 'Tragic romance', 'Period romance',
  'Coming-of-age', 'High school', 'College', 'Summer camp', 'Small-town drama',
  'Family drama', 'Divorce drama', 'Grief drama', 'Addiction drama', 'Redemption story',
  'Rags to riches', 'Fall from grace', 'Cautionary tale', 'Fable', 'Origin myth',
  'Heist', 'Heist gone wrong', 'Caper', 'Bank robbery', 'Art forgery',
  'Con artist', 'Gambling', 'Mob story', 'Prison break', 'Hostage drama',
  'Home invasion', 'Kidnapping', 'Revenge', 'Vigilante', 'Assassin',
  'Spy thriller', 'Conspiracy thriller', 'Political thriller', 'Psychological thriller', 'Whistleblower',
  'Courtroom drama', 'Legal drama', 'Medical drama', 'Newsroom drama', 'Election',
  'Mystery', 'Whodunit', 'Cozy mystery', 'Cold case', 'Locked-room mystery',
  'Slasher', 'Haunted house', 'Ghost story', 'Exorcism', 'Cult',
  'Folk horror', 'Cosmic horror', 'Body horror', 'Creature feature', 'Techno-horror',
  'Eco-horror', 'Zombie', 'Vampire', 'Werewolf', 'Monster-of-the-week',
  'Disaster movie', 'Survival', 'Post-apocalyptic', 'Pandemic', 'Dystopia',
  'Time travel', 'Time loop', 'Multiverse', 'Memory erasure', 'Dream heist',
  'Alien invasion', 'First contact', 'Space opera', 'Space western', 'Asteroid mining',
  'Cyberpunk', 'Steampunk', 'AI uprising', 'Robot rebellion', 'Clone drama',
  'Virtual reality', 'Video game world', 'Superhero', 'Superhero origin', 'Kaiju',
  'Fantasy quest', 'Sword and sorcery', 'Fairy tale', 'Chosen one', 'Dark fantasy',
  'Western', 'Samurai', 'Martial arts', 'Wuxia', 'Gladiator',
  'War movie', 'Anti-war', 'Submarine movie', 'Resistance', 'POW escape',
  'Sports underdog', 'Boxing movie', 'Racing', 'Chess', 'Poker',
  'Road trip', 'Treasure hunt', 'Jungle expedition', 'Arctic expedition', 'Deep-sea expedition',
  'Lost city', 'Pirates', 'Adventure serial', 'Mountain climbing', 'Shipwreck',
  'Musical', 'Jukebox musical', 'Rock opera', 'Biopic', 'Historical epic',
  'Mentor and student', 'Father and son', 'Mother and daughter', 'Sibling rivalry', 'Found family',
  'Holiday movie', 'Christmas movie', 'Halloween special', 'Cooking competition', 'Talent show',
  'Reality dating show', 'Game show', 'Nature documentary', 'True crime', 'Noir',
  'Neo-noir', 'Erotic thriller', 'Slice of life', 'Anthology', 'Midlife crisis',
  'Retirement home', 'Babysitting', 'Roommates', 'Neighbors feud', 'Small business',
  'Startup', 'Restaurant', 'Food truck', 'Wedding planner', 'Funeral',
];

// Leads that are expensive or impossible in live action but trivial to
// generate: creatures, machines, myths, objects that talk, people who are not
// people. Written as a noun phrase that takes an article ("a", "an").
export const CHARACTERS = [
  'mermaid', 'merman', 'siren', 'selkie', 'kelpie',
  'water nymph', 'Atlantean', 'fish-man', 'jellyfish person', 'anglerfish',
  'giant octopus', 'kraken', 'sea serpent', 'narwhal', 'whale',
  'rusty maintenance robot', 'chrome android', 'robot roommate', 'robot butler', 'combat robot on parole',
  'sentient vending machine', 'sentient toaster', 'sentient smartphone', 'sentient elevator', 'sentient traffic light',
  'sentient spaceship', 'sentient house', 'sentient car', 'AI assistant with a body', 'nanobot swarm',
  'hologram', 'glitchy hologram', 'video game NPC', 'pixel-art hero', 'low-poly character',
  'cyborg', 'mech pilot', 'giant mech', 'clone', 'army of clones',
  'grey alien', 'tall glowing alien', 'insectoid alien', 'gelatinous alien', 'alien exchange student',
  'alien diplomat', 'alien tourist', 'alien intern', 'alien who is very small', 'alien parasite',
  'astronaut stranded on Mars', 'moon colonist', 'space pirate', 'space trucker', 'asteroid miner',
  'ghost', 'poltergeist', 'Victorian ghost', 'ghost of a dog', 'banshee',
  'skeleton', 'mummy', 'mummified pharaoh', 'vampire', 'werewolf',
  'Frankenstein-style monster', 'swamp creature', 'Bigfoot', 'yeti', 'Loch Ness monster',
  'chupacabra', 'Mothman', 'jackalope', 'wendigo', 'kitsune fox spirit',
  'tanuki', 'kappa', 'oni', 'tengu', 'thunderbird',
  'dragon', 'baby dragon', 'griffin', 'phoenix', 'unicorn',
  'pegasus', 'centaur', 'minotaur', 'satyr', 'sphinx',
  'medusa', 'cyclops', 'giant', 'ogre', 'troll',
  'goblin', 'gnome', 'fairy', 'pixie', 'elf',
  'dwarf', 'wizard', 'witch', 'necromancer', 'genie',
  'angel', 'fallen angel', 'demon', 'the Devil', 'the Grim Reaper',
  'Death personified', 'Time personified', 'the Moon personified', 'the Sun personified', 'talking black hole',
  'cloud person', 'living shadow', 'invisible man', 'man made of water', 'man made of fire',
  'rock golem', 'clay golem', 'sand golem', 'lava monster', 'ice giant',
  'fire elemental', 'tornado with a face', 'sentient weather system', 'northern lights spirit', 'living snowman',
  'scarecrow', 'living mannequin', 'ventriloquist dummy', 'living statue', 'gargoyle',
  'living painting', 'cartoon character in the real world', 'claymation figure', 'paper cutout person', 'origami crane',
  'brick-toy figure', 'puppet', 'marionette', 'sock puppet', 'haunted doll',
  'nutcracker', 'toy soldier', 'teddy bear come to life', 'plush dinosaur', 'action figure',
  'talking cat', 'talking dog', 'talking horse', 'talking goldfish', 'talking crow',
  'talking houseplant', 'talking teapot', 'talking sword', 'living book', 'sentient map',
  'giant ant', 'giant spider', 'giant snail', 'kaiju', 'city-sized lizard',
  'dinosaur', 'velociraptor', 'T-rex', 'woolly mammoth', 'sabre-tooth tiger',
  'dodo', 'octopus', 'sloth', 'capybara', 'raccoon',
  'bear', 'polar bear', 'penguin', 'ostrich', 'moth',
  'butterfly', 'bee queen', 'ant colony', 'sentient fungus', 'mushroom person',
  'tree person', 'walking cactus', 'carnivorous plant', 'dryad', 'cloud whale',
  'sky jellyfish', 'time traveler from the year 3000', 'caveman in the present day', 'Roman centurion in the present day', 'knight in full armor',
  'Viking', 'samurai ghost', 'pharaoh', 'dinosaur in a suit', 'bear in a suit',
  'shark in a suit', 'two kids in a trench coat', 'sentient hat', 'living tattoo', 'reflection that acts on its own',
  'shadow that detached from its owner', 'imaginary friend', 'tooth fairy', 'sandman', 'bogeyman',
  'Krampus', "Santa's elf", 'reindeer', 'snow queen', 'frog prince',
  'swan princess', 'Big Bad Wolf', 'gingerbread man', 'leprechaun', 'wizard\'s familiar',
  'sentient cloud of bees', 'fog with intentions', 'living oil painting of a duke', 'a stack of sentient pancakes', 'talking moon rock',
];

// Familiar formats, eras, and looks. Written so "in the style of X" reads.
export const STYLES = [
  'multi-cam sitcom', 'single-camera sitcom', 'mockumentary', 'vlog', 'found footage',
  'security-camera footage', 'bodycam footage', 'dashcam footage', 'video-call movie', 'told entirely through screens',
  'vertical short-form video', 'YouTube apology video', 'livestream', 'reality-TV confessional', 'cooking show',
  'home shopping channel', 'late-night talk show', 'local news broadcast', 'weather report', 'infomercial',
  'public-access TV', '1950s educational film', 'wartime newsreel', 'silent film', 'German expressionism',
  'film noir', 'Technicolor musical', 'spaghetti western', 'French New Wave', 'Italian neorealism',
  '70s paranoid thriller', '80s synth action', '80s high-school movie', '90s indie slacker', 'direct-to-video 90s action',
  'early-2000s teen comedy', 'mumblecore', 'symmetrical dollhouse', 'one-point-perspective dread', 'dream logic',
  'chaptered crime saga', 'deadpan midwestern', 'maximalist blockbuster', 'non-linear puzzle', 'slow-burn elevated horror',
  'made-for-TV Christmas movie', 'telenovela', 'K-drama', 'Bollywood musical', 'Nollywood',
  'Hong Kong action', 'tokusatsu', 'shonen anime', 'slice-of-life anime', 'watercolor animation',
  'Saturday-morning cartoon', 'rubber-hose cartoon', 'claymation', 'stop-motion felt', 'paper-cutout animation',
  'rotoscope', 'pixel art', 'low-poly PS1', 'cel-shaded video game', 'machinima',
  'puppet show', 'felt puppets', 'kids\' educational show', 'nature documentary', 'true-crime docuseries',
  'slow zoom on old photographs', 'courtroom TV', 'police procedural', 'hospital drama', 'soap opera',
  'prestige cable drama', 'limited series', 'anthology episode', 'bottle episode', 'musical episode',
  'holiday special', 'clip show', 'prequel', 'sequel nobody asked for', 'gritty reboot',
  'trailer only', 'recap of a show that doesn\'t exist', 'cold open', 'post-credits scene', 'behind-the-scenes featurette',
  'audio commentary track', 'video essay', 'podcast with visuals', 'radio drama', 'epic poem narration',
  'Shakespearean', 'Greek chorus', 'opera', 'ballet', 'music video',
  'perfume commercial', 'car commercial', 'pharmaceutical commercial', 'airline safety video', 'corporate training video',
  'unboxing video', 'ASMR', 'speedrun', 'Let\'s Play', 'wedding video',
  'home movie on VHS', 'Super 8 vacation film', 'Polaroid slideshow', 'Instagram story', 'PowerPoint presentation',
  'TED talk', 'stand-up special', 'improv show', 'sketch show', 'game show',
  'dating show', 'survival competition', 'single continuous take', 'split screen', 'black and white',
  'sepia', 'neon-soaked', 'overexposed dream', 'fisheye lens', 'drone footage',
  'GoPro', 'IMAX spectacle', '3D gimmick', 'shot on a flip phone', 'shot on a thermal camera',
  'shot from the point of view of a Roomba', 'shot from inside a fish tank', 'shot from a doorbell camera', 'court sketch artist', 'stained glass',
];
